INSERT INTO public.books (id, title, author, description, cover_url, pdf_preview_url, available) VALUES
('e14bc01f-41ff-476e-a47c-5fca03dbe3be', 'How Europe Underdeveloped Africa', 'Walter Rodney', 'Critique historique du pillage économique colonial et du sous-développement imposé à l''Afrique.', 'https://m.media-amazon.com/images/I/71T4H1EwZML.jpg', 'https://archive.org/details/howeuropeunderde00rodn', true),
('3df96c26-8d12-4b1b-8939-c5ae3ae5c3cb', 'The Groundings with My Brothers', 'Walter Rodney', 'Textes politiques fondamentaux sur la solidarité afro-caribéenne et l''activisme panafricain.', 'https://m.media-amazon.com/images/I/81p-MgKqfKL.jpg', 'https://archive.org/details/groundingswithmy0000rodn', true),
('43db8f12-ea6d-434f-9849-fd80ce20424f', 'African Philosophy in Search of Identity', 'D. A. Masolo', 'Réflexion sur les tensions entre authenticité africaine et philosophie universelle.', 'https://m.media-amazon.com/images/I/71hB34XvymL.jpg', 'https://archive.org/details/africanphilosoph0000maso', true),
('d6fc5405-bd61-49eb-9b65-2fcf93063e1d', 'African Religions & Philosophy', 'John S. Mbiti', 'Exploration des croyances religieuses africaines et leur influence philosophique.', 'https://m.media-amazon.com/images/I/710x7WDoSGL.jpg', 'https://archive.org/details/africanreligions0000mbit', true),
('9cfc753f-4594-460a-b7df-5c179405c30b', 'Sage Philosophy', 'Odera H. Oruka', 'Étude sur les philosophes traditionnels africains et leur pensée critique.', 'https://m.media-amazon.com/images/I/81TdpZTe2wL.jpg', 'https://archive.org/details/sagephilosophyin00oruk', true),
('c9fc04c3-16bb-4a9d-b61c-97a7b41cf5a3', 'A History of the Upper Guinea Coast', 'Walter Rodney', 'Analyse historique de la traite négrière sur la côte ouest-africaine.', 'https://m.media-amazon.com/images/I/71oz9j4lJXL.jpg', 'https://archive.org/details/historyofuppergu00rodn', true),
('fbdc4c76-9bbf-49d8-82de-8c23cb0e0f60', 'Essai sur la problématique philosophique dans l''Afrique actuelle', 'Marcien Towa', 'Texte fondamental de la critique de la pensée coloniale et néocoloniale africaine.', 'https://upload.wikimedia.org/wikipedia/commons/8/89/Marcien_Towa_-_Essai.jpg', 'https://www.sudoc.fr/03413646X', true),
('40cb75bc-20cc-4099-9f7f-0bb7c9560737', 'Léopold Sédar Senghor: Négritude ou Servitude?', 'Marcien Towa', 'Critique rigoureuse de la pensée de Senghor et du mouvement de la Négritude.', 'https://m.media-amazon.com/images/I/61vOZfvpy0L.jpg', 'https://www.persee.fr/doc/hom_0439-4216_1983_num_23_1_368603_t1_0103_0000_001', true),
('03ad2f8e-0b2e-4c17-85b3-7805a5de8db3', 'The Wretched of the Earth', 'Frantz Fanon', 'Ouvrage révolutionnaire sur la décolonisation, la violence et l''aliénation des colonisés.', 'https://m.media-amazon.com/images/I/81m3Aa9UGPL.jpg', 'https://archive.org/details/wretchedofearth00fran_0', true),
('acde36cd-00d1-4f8d-b529-f3701447f0fa', 'Black Skin, White Masks', 'Frantz Fanon', 'Analyse de la psychologie du colonisé et des effets du racisme sur l''identité noire.', 'https://m.media-amazon.com/images/I/710Gy8HkPZL.jpg', 'https://archive.org/details/blackskinwhitema0000fano', true);