-- Insertion de 6 nouveaux penseurs africains (Lot 2)
INSERT INTO public.thinkers (
  id,
  name,
  title,
  description,
  education,
  career,
  contributions_impact,
  vision,
  practical_impact,
  works_projects_media,
  country,
  birth_year,
  death_year,
  period,
  category_id,
  image_url,
  created_at,
  updated_at
) VALUES 
(
  '42159dcb-8ea6-4523-a021-5a13c2f6b3b3',
  'Dr. Matshidiso Moeti',
  'Médecin, Directrice régionale OMS Afrique',
  'Médecin botswanaise et première femme africaine à diriger l''OMS pour la région Afrique, elle a dirigé des réponses sanitaires majeures sur le continent.',
  'University of London (MBBS); London School of Hygiene & Tropical Medicine',
  'Directrice OMS Afrique depuis 2015; consultante auprès de l''UNICEF et ONUSIDA.',
  'Pilote la réponse aux épidémies (Ebola, COVID-19) en Afrique; renforce les systèmes de santé nationaux.',
  'Un système de santé africain autonome, intégré, et résilient.',
  'A accru l''accès à la vaccination et préparé des cadres de réponse sanitaire souverains.',
  '{"WHO Leadership Biography": "https://www.afro.who.int/about-us/leadership/dr-matshidiso-moeti"}',
  'Botswana',
  1954,
  null,
  '20th–21st century',
  'c9208c84-ca95-4d7e-8c69-dd54b44982f8', -- Médecins
  'https://upload.wikimedia.org/wikipedia/commons/4/40/Matshidiso_Moeti.jpg',
  now(),
  now()
),
(
  'a6827f3e-749b-4ad5-8ec2-dbdc395946fd',
  'Ousmane Sembène',
  'Réalisateur, Écrivain',
  'Pionnier du cinéma africain, considéré comme le « père du cinéma africain » pour avoir porté les voix africaines à l''écran avec fierté et authenticité.',
  'École de formation de cinéma de Moscou (VGIK)',
  'Réalisateur, romancier, scénariste, syndicaliste engagé.',
  'Ses films ont décolonisé le regard sur l''Afrique et donné une voix aux classes populaires.',
  'Faire du cinéma un outil de libération pour les masses africaines.',
  'Ses œuvres sont étudiées dans le monde entier et projetées dans les festivals africains majeurs.',
  '{"La Noire de... (1966)": "https://en.wikipedia.org/wiki/Black_Girl_(1966_film)", "Moolaadé (2004)": "https://www.imdb.com/title/tt0416991/"}',
  'Sénégal',
  1923,
  2007,
  '20th–21st century',
  '7ae1e30a-5110-4cd7-92c2-34083bc1a928', -- Cinéastes
  'https://upload.wikimedia.org/wikipedia/commons/5/5c/Ousmane_Sembene.jpg',
  now(),
  now()
),
(
  '2e8c5ed2-2283-49c5-8a61-02887c58603d',
  'William Kamkwamba',
  'Inventeur, Ingénieur autodidacte',
  'Jeune Malawite devenu célèbre pour avoir construit une éolienne à partir de matériaux recyclés pour alimenter son village en électricité.',
  'Dartmouth College (USA)',
  'Auteur, ingénieur, conférencier TED. Promoteur de l''innovation communautaire africaine.',
  'A démontré la capacité d''ingéniosité africaine face à la pauvreté et au manque d''accès à l''énergie.',
  'Un avenir alimenté par les idées et les ressources africaines locales.',
  'Son modèle a inspiré des programmes STEM en Afrique rurale.',
  '{"The Boy Who Harnessed the Wind (2009)": "https://williamkamkwamba.typepad.com/", "Film Netflix (2019)": "https://www.netflix.com/title/80200047"}',
  'Malawi',
  1987,
  null,
  '21st century',
  'cf858246-92ec-4990-af94-9456a70e7a32', -- Inventeurs
  'https://upload.wikimedia.org/wikipedia/commons/7/79/William_Kamkwamba.jpg',
  now(),
  now()
),
(
  'f2a2ac99-c730-4f9d-a8d0-bb4f5026822e',
  'Fatou Bensouda',
  'Juriste, Ex-procureure de la CPI',
  'Juriste gambienne, première femme africaine procureure de la Cour pénale internationale, elle a œuvré pour la justice globale avec rigueur et intégrité.',
  'University of Ife (Nigeria); International Maritime Law Institute (Malte)',
  'Procureure générale de Gambie; Procureure de la CPI de 2012 à 2021.',
  'A représenté l''Afrique avec compétence dans les sphères judiciaires internationales.',
  'Promouvoir une justice mondiale équitable, sans deux poids deux mesures.',
  'A renforcé les capacités juridiques des États africains au sein des institutions internationales.',
  '{"Profile at ICC": "https://www.icc-cpi.int/about/prosecutor/fatou-bensouda"}',
  'Gambie',
  1961,
  null,
  '20th–21st century',
  'bd787724-4fc0-437f-9dd0-219a77ea692b', -- Juristes
  'https://upload.wikimedia.org/wikipedia/commons/a/a3/Fatou_Bensouda.jpg',
  now(),
  now()
),
(
  'ac0aa3e9-210e-47c3-8653-3e9f176d5c17',
  'Strive Masiyiwa',
  'Entrepreneur, Philanthrope',
  'Magnat zimbabwéen des télécoms, pionnier de la connectivité mobile en Afrique et mécène de l''éducation panafricaine.',
  'University of Wales',
  'Fondateur d''Econet Wireless; membre du conseil de Netflix et Unilever.',
  'A permis l''accès au téléphone mobile à des millions d''Africains. Grand financeur de bourses africaines.',
  'Une Afrique connectée et instruite grâce à la technologie et à l''entrepreneuriat éthique.',
  'Des dizaines de milliers d''étudiants africains soutenus par ses bourses.',
  '{"Econet Group": "https://www.econetafrica.com/", "Higherlife Foundation": "https://www.higherlifefoundation.com/"}',
  'Zimbabwe',
  1961,
  null,
  '20th–21st century',
  '7c9e13f6-8610-46c1-856d-0d63805945ac', -- Entrepreneurs
  'https://upload.wikimedia.org/wikipedia/commons/d/d4/Strive_Masiyiwa_World_Economic_Forum.jpg',
  now(),
  now()
),
(
  '56d2ae9a-3949-4a57-8217-62161488b960',
  'Dr. Akinwumi Adesina',
  'Économiste, Président de la Banque Africaine de Développement',
  'Économiste nigérian reconnu pour son leadership en matière de financement du développement agricole africain.',
  'University of Ife; PhD, Purdue University (USA)',
  'Ministre de l''Agriculture au Nigeria; Président de la BAD depuis 2015.',
  'Réformes agricoles, développement d''infrastructures rurales et financement de PME agricoles.',
  'Transformer l''Afrique par l''agriculture et l''intégration régionale.',
  'Des millions d''agriculteurs africains connectés au financement, à la technologie et aux marchés.',
  '{"AfDB Profile": "https://www.afdb.org/en/about-us/organisational-structure/president", "Forbes Africa Interview": "https://www.forbesafrica.com/"}',
  'Nigeria',
  1960,
  null,
  '20th–21st century',
  'a1f4c792-1ab4-4b3e-be4f-67f31654794c', -- Économistes
  'https://upload.wikimedia.org/wikipedia/commons/b/bd/Akinwumi_Adesina.jpg',
  now(),
  now()
);